// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVyCsLc7S_P77kLyVLFXvtFl9hlgQMgp0',
    appId: '1:378553258239:web:5b793b34f99a1ce2fe3cca',
    messagingSenderId: '378553258239',
    projectId: 'colleague-app-d0247',
    authDomain: 'colleague-app-d0247.firebaseapp.com',
    storageBucket: 'colleague-app-d0247.appspot.com',
    measurementId: 'G-CJ4HMGH9SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAovNjdWttfmZFm4mYOAM0GmFANNU6r75E',
    appId: '1:378553258239:android:aba6c0226f6eb041fe3cca',
    messagingSenderId: '378553258239',
    projectId: 'colleague-app-d0247',
    storageBucket: 'colleague-app-d0247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdyx2wty-PzWXs_-VXLELSuunhMo5Us5k',
    appId: '1:378553258239:ios:d1e77e3aed9d22b6fe3cca',
    messagingSenderId: '378553258239',
    projectId: 'colleague-app-d0247',
    storageBucket: 'colleague-app-d0247.appspot.com',
    iosBundleId: 'com.example.colleagueapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdyx2wty-PzWXs_-VXLELSuunhMo5Us5k',
    appId: '1:378553258239:ios:d1e77e3aed9d22b6fe3cca',
    messagingSenderId: '378553258239',
    projectId: 'colleague-app-d0247',
    storageBucket: 'colleague-app-d0247.appspot.com',
    iosBundleId: 'com.example.colleagueapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVyCsLc7S_P77kLyVLFXvtFl9hlgQMgp0',
    appId: '1:378553258239:web:b4206ed6c8c48345fe3cca',
    messagingSenderId: '378553258239',
    projectId: 'colleague-app-d0247',
    authDomain: 'colleague-app-d0247.firebaseapp.com',
    storageBucket: 'colleague-app-d0247.appspot.com',
    measurementId: 'G-K99TLERJT9',
  );
}
